function [subjID, dominant_hand, speed, trial, nellipse, x, y, Velocity, Pressure, Radius, t] = importfileZarandi(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [SUBJID, DOMINANT_HAND, SPEED, TRIAL, NELLIPSE, X, Y, VELOCITY,
%  PRESSURE, RADIUS, T] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [SUBJID, DOMINANT_HAND, SPEED, TRIAL, NELLIPSE, X, Y, VELOCITY,
%  PRESSURE, RADIUS, T] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [subjID, dominant_hand, speed, trial, nellipse, x, y, Velocity, Pressure, Radius, t] = importfile("D:\DROPBOX\Dropbox\Brain2Bee\PowerLawToolChain\_RawDataZarandi\IJCNN2022_Ellipses-main\IJCNN2022_Ellipses-main\data\subject0.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Jun-2023 13:40:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["subjID", "dominant_hand", "speed", "trial", "nellipse", "x", "y", "Velocity", "Pressure", "Radius", "t"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
subjID = tbl.subjID;
dominant_hand = tbl.dominant_hand;
speed = tbl.speed;
trial = tbl.trial;
nellipse = tbl.nellipse;
x = tbl.x;
y = tbl.y;
Velocity = tbl.Velocity;
Pressure = tbl.Pressure;
Radius = tbl.Radius;
t = tbl.t;
end